---
nfs_exports: ["/home/ubuntu    *(rw,sync,no_root_squash)"]
client_nfs_prefix: "/nfss"
client_mount_opts: "defaults,x-systemd.automount,x-systemd.requires=network-online.target,x-systemd.device-timeout=10s"

nfs_rpcbind_state: started
nfs_rpcbind_enabled: true
